//! Example files that ship with the program, and how to find them.
//!
//! The files in `examples/` are generated by `write_all`, so they can be
//! made again whenever the writers change:
//!
//!     cargo test write_example_files -- --ignored

use std::path::{Path, PathBuf};
use std::sync::Arc;

use bevy::math::{Quat, Vec3};

use crate::core::anim::{create_test_clip, AnimData, FrameRate, Joint, Track};

pub const WALK_FBX:   &str = "walk_cycle.fbx";
pub const TAKES_DIR:  &str = "takes";
pub const SHAPES_USD: &str = "shapes.usda";
pub const TABLE_USD:  &str = "table.usda";

/// The examples folder: the one named by XMS_EXAMPLES, next to the program,
/// at the root of the source tree when run through cargo, or in the working
/// folder.
pub fn dir() -> Option<PathBuf> {
    let mut places: Vec<PathBuf> = vec![];
    if let Some(d) = std::env::var_os("XMS_EXAMPLES") { places.push(PathBuf::from(d)); }
    if let Ok(exe) = std::env::current_exe() {
        if let Some(d) = exe.parent() {
            places.push(d.join("examples"));
            // target/release/xms -> the repository
            if let Some(root) = d.parent().and_then(|p| p.parent()) { places.push(root.join("examples")); }
            if let Some(root) = d.parent().and_then(|p| p.parent()).and_then(|p| p.parent()) { places.push(root.join("examples")); }
        }
    }
    if let Ok(cwd) = std::env::current_dir() { places.push(cwd.join("examples")); }
    places.into_iter().find(|p| p.join(SHAPES_USD).is_file())
}

/// Path of an example file as a node parameter. Falls back to a relative
/// path when the folder cannot be found, so the node shows what is missing.
pub fn path(name: &str) -> String {
    dir().unwrap_or_else(|| PathBuf::from("examples")).join(name).to_string_lossy().to_string()
}

/// A take with two characters: two walkers side by side, the second half a
/// stride behind and a little smaller, each under its own root.
pub fn two_character_clip(seconds: f32, variation: f32) -> AnimData {
    let rate = FrameRate::from_fps(30.0);
    let one = create_test_clip(seconds, rate);
    let frames = one.frames;
    let mut joints: Vec<Joint> = vec![];
    let mut tracks: Vec<Track> = vec![];
    for (c, (name, x, scale, shift)) in [("Anna", -0.6, 1.0, 0usize), ("Ben", 0.6, 0.92 + 0.04 * variation, 15)].into_iter().enumerate() {
        let base = joints.len();
        let rest = bevy::prelude::Transform::from_translation(Vec3::new(x, 0.0, 0.0))
            .with_rotation(Quat::from_rotation_y(0.25 * variation * if c == 0 { 1.0 } else { -1.0 }))
            .with_scale(Vec3::splat(scale));
        let mut root = Joint::new(format!("{name}_Root"), None, rest);
        root.is_bone = false;
        joints.push(root);
        tracks.push(vec![]);
        for (j, joint) in one.joints.iter().enumerate() {
            let short = joint.name.rsplit(':').next().unwrap_or(&joint.name);
            let mut copy = Joint::new(format!("{name}:{short}"), Some(joint.parent.map(|p| base + 1 + p).unwrap_or(base)), joint.rest);
            copy.is_bone = true;
            joints.push(copy);
            tracks.push((0..frames).map(|i| one.tracks[j][(i + shift) % frames]).collect());
        }
    }
    AnimData { name: "TwoCharacters".into(), joints, tracks: Arc::new(tracks), ..one }
}

/// A few polygon meshes under transforms, as USD text.
pub fn shapes_usda() -> String {
    r#"#usda 1.0
(
    defaultPrim = "Shapes"
    upAxis = "Y"
    metersPerUnit = 1
)

def Xform "Shapes"
{
    def Mesh "Pyramid"
    {
        point3f[] points = [(-0.5, 0, -0.5), (0.5, 0, -0.5), (0.5, 0, 0.5), (-0.5, 0, 0.5), (0, 0.9, 0)]
        int[] faceVertexCounts = [4, 3, 3, 3, 3]
        int[] faceVertexIndices = [0, 1, 2, 3, 0, 4, 1, 1, 4, 2, 2, 4, 3, 3, 4, 0]
        double3 xformOp:translate = (-1.4, 0, 0)
        uniform token[] xformOpOrder = ["xformOp:translate"]
    }

    def Mesh "Prism"
    {
        point3f[] points = [(-0.4, 0, -0.5), (0.4, 0, -0.5), (0, 0.7, -0.5), (-0.4, 0, 0.5), (0.4, 0, 0.5), (0, 0.7, 0.5)]
        int[] faceVertexCounts = [3, 3, 4, 4, 4]
        int[] faceVertexIndices = [0, 2, 1, 3, 4, 5, 0, 1, 4, 3, 1, 2, 5, 4, 2, 0, 3, 5]
    }

    def Mesh "Octahedron"
    {
        point3f[] points = [(0.5, 0.5, 0), (-0.5, 0.5, 0), (0, 1, 0), (0, 0, 0), (0, 0.5, 0.5), (0, 0.5, -0.5)]
        int[] faceVertexCounts = [3, 3, 3, 3, 3, 3, 3, 3]
        int[] faceVertexIndices = [0, 2, 4, 2, 1, 4, 1, 3, 4, 3, 0, 4, 2, 0, 5, 1, 2, 5, 3, 1, 5, 0, 3, 5]
        double3 xformOp:translate = (1.4, 0, 0)
        uniform token[] xformOpOrder = ["xformOp:translate"]
    }
}
"#.to_string()
}

/// A table: a top and four legs, each its own mesh under one transform.
pub fn table_usda() -> String {
    // A box as eight points and six quads.
    let boxed = |name: &str, c: [f32; 3], h: [f32; 3]| -> String {
        let p: Vec<String> = [[-1, -1, -1], [1, -1, -1], [1, 1, -1], [-1, 1, -1], [-1, -1, 1], [1, -1, 1], [1, 1, 1], [-1, 1, 1]]
            .iter().map(|s| format!("({}, {}, {})", c[0] + s[0] as f32 * h[0], c[1] + s[1] as f32 * h[1], c[2] + s[2] as f32 * h[2])).collect();
        format!(
"    def Mesh \"{name}\"
    {{
        point3f[] points = [{}]
        int[] faceVertexCounts = [4, 4, 4, 4, 4, 4]
        int[] faceVertexIndices = [0, 3, 2, 1, 4, 5, 6, 7, 0, 1, 5, 4, 1, 2, 6, 5, 2, 3, 7, 6, 3, 0, 4, 7]
    }}
", p.join(", "))
    };
    let mut out = String::from("#usda 1.0\n(\n    defaultPrim = \"Table\"\n    upAxis = \"Y\"\n    metersPerUnit = 1\n)\n\ndef Xform \"Table\"\n{\n");
    out += &boxed("Top", [0.0, 0.74, 0.0], [0.8, 0.03, 0.45]);
    for (i, (x, z)) in [(-0.72, -0.37), (0.72, -0.37), (0.72, 0.37), (-0.72, 0.37)].into_iter().enumerate() {
        out += "\n";
        out += &boxed(&format!("Leg{}", i + 1), [x, 0.355, z], [0.04, 0.355, 0.04]);
    }
    out += "}\n";
    out
}

/// Write every example file into `dir`. Returns the files written.
pub fn write_all(dir: &Path) -> std::io::Result<Vec<PathBuf>> {
    std::fs::create_dir_all(dir.join(TAKES_DIR))?;
    let mut out = vec![];

    let mut walk = create_test_clip(2.0, FrameRate::from_fps(30.0));
    walk.name = "WalkCycle".into();
    let p = dir.join(WALK_FBX);
    crate::fbx_writer::write_fbx(&p, &walk, true)?;
    out.push(p);

    for (n, (seconds, variation)) in [(2.0, 0.0), (3.0, 1.0), (1.5, -1.0)].into_iter().enumerate() {
        let p = dir.join(TAKES_DIR).join(format!("take_{:03}.fbx", n + 1));
        crate::fbx_writer::write_fbx(&p, &two_character_clip(seconds, variation), true)?;
        out.push(p);
    }

    for (name, text) in [(SHAPES_USD, shapes_usda()), (TABLE_USD, table_usda())] {
        let p = dir.join(name);
        std::fs::write(&p, text)?;
        out.push(p);
    }
    Ok(out)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::core::poly::PolyMesh;

    #[test]
    fn usd_examples_parse_into_closed_meshes() {
        let shapes = crate::usd_loader::parse_usda_meshes(&shapes_usda()).unwrap();
        assert_eq!(shapes.len(), 3);
        let table = crate::usd_loader::parse_usda_meshes(&table_usda()).unwrap();
        assert_eq!(table.len(), 5);
        for (name, mesh) in shapes.iter().chain(table.iter()) {
            assert!(!mesh.vertices.is_empty() && !mesh.indices.is_empty(), "{name} is empty");
        }
        // The text itself describes closed, outward-facing solids.
        for text in [shapes_usda(), table_usda()] {
            for block in text.split("def Mesh").skip(1) {
                let list = |key: &str| -> Vec<f32> {
                    let s = &block[block.find(key).unwrap()..];
                    let s = &s[s.find('[').unwrap() + 1..];
                    // "points = [" follows the "[]" of the type.
                    let s = if s.starts_with(']') { &s[s.find('[').unwrap() + 1..] } else { s };
                    s[..s.find(']').unwrap()].split(|c: char| c == ',' || c == '(' || c == ')' || c.is_whitespace())
                        .filter(|t| !t.is_empty()).map(|t| t.parse().unwrap()).collect()
                };
                let pts = list("point3f[] points");
                let counts = list("int[] faceVertexCounts");
                let idx = list("int[] faceVertexIndices");
                let mut polys = vec![];
                let mut at = 0;
                for c in counts { polys.push(idx[at..at + c as usize].iter().map(|i| *i as u32).collect()); at += c as usize; }
                assert_eq!(at, idx.len());
                let m = PolyMesh { verts: pts.chunks(3).map(|p| Vec3::new(p[0], p[1], p[2])).collect(), polys };
                assert!(m.is_closed(), "open mesh in {}", &block[..20]);
                assert!(m.volume() > 0.0, "inside-out mesh in {}", &block[..20]);
            }
        }
    }

    #[test]
    fn two_character_take_splits_in_two() {
        let clip = two_character_clip(1.0, 0.0);
        let roots = clip.character_roots();
        assert_eq!(roots.len(), 2);
        assert_eq!(clip.character_name(roots[0]), "Anna");
        assert_eq!(clip.character_name(roots[1]), "Ben");
        assert_eq!(clip.split(roots[1]).joints.len(), 20);
        assert_eq!(clip.frames, 30);
    }

    #[test]
    fn example_files_read_back() {
        let dir = std::env::temp_dir().join("xms_examples_test");
        let _ = std::fs::remove_dir_all(&dir);
        let files = write_all(&dir).unwrap();
        assert_eq!(files.len(), 6);
        let walk = crate::fbx_loader::load_fbx(&dir.join(WALK_FBX).to_string_lossy(), 0).unwrap();
        assert_eq!(walk.anim.joints.iter().filter(|j| j.is_bone).count(), 19);
        assert_eq!(walk.anim.frames, 60);
        let takes = crate::fbx_loader::list_fbx(&dir.join(TAKES_DIR).to_string_lossy());
        assert_eq!(takes.len(), 3);
        for t in takes {
            let take = crate::fbx_loader::load_fbx(&t.to_string_lossy(), 0).unwrap();
            assert_eq!(take.anim.character_roots().len(), 2, "{}", t.display());
        }
        assert_eq!(crate::usd_loader::load_usd_meshes(&dir.join(TABLE_USD)).unwrap().len(), 5);
    }

    /// Regenerates the files in `examples/`. Run on purpose, not with the suite.
    #[test]
    #[ignore]
    fn write_example_files() {
        let dir = std::env::current_dir().unwrap().join("examples");
        for f in write_all(&dir).unwrap() { println!("wrote {}", f.display()); }
    }
}
